spring.application.name=HamroKitab2


spring.datasource.url=jdbc:mysql:// gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test 
spring.datasource.username=PmJmgKQ3HC6gR39.root
spring.datasource.password=hetxToON3VakCBoc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shramika47@gmail.com
spring.mail.password=jhta njam gtvw qnaq

# Other properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# TLS , port 587
spring.mail.properties.mail.smtp.starttls.enable=true